run:
  timeout: 1m
  tests: true
  go: '1.22'

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck
    - gosimple
    - unused
    - ineffassign
    - gofmt
    - goimports
    - revive
    - typecheck

output:
  format: colored-line-number

linters-settings:
  govet:
    check-shadowing: false
    enable-all: true