// Code generated by mockery. DO NOT EDIT.

package wifi_mocks

import (
	wifi "github.com/mdlayher/wifi"
	mock "github.com/stretchr/testify/mock"
)

// WiFiHandle is an autogenerated mock type for the WiFiHandle type
type WiFiHandle struct {
	mock.Mock
}

// Interfaces provides a mock function with given fields:
func (_m *WiFiHandle) Interfaces() ([]*wifi.Interface, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Interfaces")
	}

	var r0 []*wifi.Interface
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*wifi.Interface, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*wifi.Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*wifi.Interface)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StationInfo provides a mock function with given fields: ifi
func (_m *WiFiHandle) StationInfo(ifi *wifi.Interface) (*wifi.StationInfo, error) {
	ret := _m.Called(ifi)

	if len(ret) == 0 {
		panic("no return value specified for StationInfo")
	}

	var r0 *wifi.StationInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(*wifi.Interface) (*wifi.StationInfo, error)); ok {
		return rf(ifi)
	}
	if rf, ok := ret.Get(0).(func(*wifi.Interface) *wifi.StationInfo); ok {
		r0 = rf(ifi)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*wifi.StationInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(*wifi.Interface) error); ok {
		r1 = rf(ifi)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewWiFiHandle creates a new instance of WiFiHandle
func NewWiFiHandle(t interface {
	mock.TestingT
	Cleanup(func())
}) *WiFiHandle {
	mock := &WiFiHandle{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
